name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Install dependencies
        run: |
          npm install
          echo "🎉 Installation complete..!"

      - name: Build package
        run: |
          npm run build
          echo "🎉 Build succeeded..!"

      - name: Get current version from package.json
        id: package_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV 

      - name: Check if version is already published
        id: check_version
        run: |
          if npm show YOUR_PACKAGE_NAME@$VERSION > /dev/null 2>&1; then
            echo "VERSION_EXISTS=true" >> $GITHUB_ENV
          else
            echo "VERSION_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Publish to npm
        if: env.VERSION_EXISTS == 'false'
        run: |
          npm publish --access public
          echo "🎉 Package published..! 🎉"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}